name: app_movil_pos
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  url_strategy: ^0.3.0
  slang: ^4.3.0
  slang_flutter: ^4.3.0
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  extended_image: ^9.0.7
  flutter_secure_storage: ^9.2.2
  connectivity_plus: ^6.1.0
  flutter_svg: ^2.0.16
  intl: ^0.19.0
  graphql: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  flutter_gen: ^5.7.0
  slang_build_runner: ^4.3.0

flutter:

  uses-material-design: true

flutter_gen:
  output: lib/app/generated/ # Optional (default: lib/gen/)
  integrations:
    flutter_svg: true