// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbAlquilerServiciosPorFactura
{
    public Guid facDet_Id { get; set; }

    public Guid alq_Id { get; set; }

    public virtual tbAlquilerServicios alq { get; set; }

    public virtual tbFacturaDetalle facDet { get; set; }
}