// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbAlquilerServicios
{
    public Guid alq_Id { get; set; }

    public string alq_Titulo { get; set; }

    public string alq_Descripcion { get; set; }

    public decimal alq_Precio { get; set; }

    public Guid user_Id { get; set; }

    public Guid tran_Id { get; set; }

    public Guid tiemp_Id { get; set; }

    public Guid estAlq_Id { get; set; }

    public virtual tbEstadoAlquilerServicios estAlq { get; set; }

    public virtual ICollection<tbAlquilerServiciosPorFactura> tbAlquilerServiciosPorFactura { get; set; } = new List<tbAlquilerServiciosPorFactura>();

    public virtual ICollection<tbCategoriaPorAlquilar> tbCategoriaPorAlquilar { get; set; } = new List<tbCategoriaPorAlquilar>();

    public virtual tbTiempo tiemp { get; set; }

    public virtual tbTransaccion tran { get; set; }

    public virtual tbUsuarios user { get; set; }
}