// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbCategoriaItem
{
    public Guid catgItem_Id { get; set; }

    public Guid catg_Id { get; set; }

    public Guid user_Id { get; set; }

    public virtual tbCategoria catg { get; set; }

    public virtual tbUsuarios user { get; set; }
}