// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbCategoria
{
    public Guid catg_Id { get; set; }

    public string catg_Nombre { get; set; }

    public virtual ICollection<tbCategoriaItem> tbCategoriaItem { get; set; } = new List<tbCategoriaItem>();

    public virtual ICollection<tbFiltroCategoriaTipo> tbFiltroCategoriaTipo { get; set; } = new List<tbFiltroCategoriaTipo>();

    public virtual ICollection<tbSubCategoria> tbSubCategoria { get; set; } = new List<tbSubCategoria>();
}