// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbCatalogoPorUsuario
{
    public Guid catUsua_Id { get; set; }

    public Guid tipCatg_Id { get; set; }

    public Guid tipUs_Id { get; set; }

    public virtual tbTipoCatalogo tipCatg { get; set; }

    public virtual tbTipoUsuario tipUs { get; set; }
}