// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbCatalogoImagen
{
    public Guid catImg_Id { get; set; }

    public Guid tipImg_Id { get; set; }

    public Guid tran_Id { get; set; }

    public string catImg_Ruta { get; set; }

    public virtual tbTipoImagen tipImg { get; set; }

    public virtual tbTransaccion tran { get; set; }
}