// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbDepartamento
{
    public Guid dept_Id { get; set; }

    public string dept_Nombre { get; set; }

    public Guid pais_Id { get; set; }

    public int dept_NuIdentidad { get; set; }

    public virtual tbPais pais { get; set; }

    public virtual ICollection<tbMunicipio> tbMunicipio { get; set; } = new List<tbMunicipio>();
}