// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbDesperdicio
{
    public Guid desp_Id { get; set; }

    public string desp_Nombre { get; set; }

    public string desp_Descripcion { get; set; }

    public Guid user_Id { get; set; }

    public int desp_Codigo { get; set; }

    public Guid tran_Id { get; set; }

    public DateOnly serv_FechaCreacion { get; set; }

    public bool desp_Gratis { get; set; }

    public virtual ICollection<tbDesperdicioPorFactura> tbDesperdicioPorFactura { get; set; } = new List<tbDesperdicioPorFactura>();

    public virtual tbTransaccion tran { get; set; }

    public virtual tbUsuarios user { get; set; }

    public virtual ICollection<tbProducto> prod { get; set; } = new List<tbProducto>();

    public virtual ICollection<tbServicio> serv { get; set; } = new List<tbServicio>();
}