// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbEvento
{
    public Guid even_Id { get; set; }

    public string even_Titulo { get; set; }

    public string even_Descripcion { get; set; }

    public DateTime even_FechaInicio { get; set; }

    public DateTime? even_FechaFin { get; set; }

    public Guid user_Id { get; set; }

    public Guid tran_Id { get; set; }

    public Guid EstEven_Id { get; set; }

    public Guid ubc_Id { get; set; }

    public virtual tbEstadoEvento EstEven { get; set; }

    public virtual tbTransaccion tran { get; set; }

    public virtual tbUbicacion ubc { get; set; }

    public virtual tbUsuarios user { get; set; }

    public virtual ICollection<tbUsuarios> userNavigation { get; set; } = new List<tbUsuarios>();
}