// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbExperiencia
{
    public Guid exp_Id { get; set; }

    public Guid ariaP_Id { get; set; }

    public bool exp_Opcional { get; set; }

    public Guid vac_Id { get; set; }

    public virtual tbAriaPuesto ariaP { get; set; }

    public virtual tbVacante vac { get; set; }
}