// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbFacturaDetalle
{
    public Guid facDet_Id { get; set; }

    public Guid fac_Id { get; set; }

    public Guid tipCatg_Id { get; set; }

    public string facDet_Codigo { get; set; }

    public int facDet_Cantidad { get; set; }

    public string facDet_Descripcion { get; set; }

    public decimal facDet_PrecioUnitario { get; set; }

    public decimal facDet_Descuento { get; set; }

    public decimal facDet_Impuesto { get; set; }

    public decimal facDet_PorcentajeImpuestos { get; set; }

    public decimal facDet_TotalPagar { get; set; }

    public virtual tbFactura fac { get; set; }

    public virtual tbAlquilerServiciosPorFactura tbAlquilerServiciosPorFactura { get; set; }

    public virtual tbDesperdicioPorFactura tbDesperdicioPorFactura { get; set; }

    public virtual tbHabilidadPorFactura tbHabilidadPorFactura { get; set; }

    public virtual tbProductoPorFactura tbProductoPorFactura { get; set; }

    public virtual tbServicioPorFactura tbServicioPorFactura { get; set; }

    public virtual tbTipoCatalogo tipCatg { get; set; }
}