// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbFactura
{
    public Guid fac_Id { get; set; }

    public string fac_NombreCliente { get; set; }

    public string fac_FacturaCAI { get; set; }

    public DateTime fac_FechaCreacio { get; set; }

    public DateTime fac_Fecha { get; set; }

    public decimal fac_SubTotal { get; set; }

    public decimal fac_Descuento { get; set; }

    public decimal fac_Impuesto { get; set; }

    public decimal fac_PorcentajeImpuestos { get; set; }

    public decimal fac_TotalPagar { get; set; }

    public string fac_RTN { get; set; }

    public Guid user_Id { get; set; }

    public Guid tran_Id { get; set; }

    public Guid? user_IdCliente { get; set; }

    public Guid tipPag_Id { get; set; }

    public virtual ICollection<tbFacturaDetalle> tbFacturaDetalle { get; set; } = new List<tbFacturaDetalle>();

    public virtual tbTipoPago tipPag { get; set; }

    public virtual tbTransaccion tran { get; set; }

    public virtual tbUsuarios user { get; set; }

    public virtual tbUsuarios user_IdClienteNavigation { get; set; }
}