// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbHabilidad
{
    public Guid hab_Id { get; set; }

    public string hab_Titulo { get; set; }

    public string hab_Descripcion { get; set; }

    public decimal? hab_Precio { get; set; }

    public Guid user_Id { get; set; }

    public Guid tran_Id { get; set; }

    public virtual ICollection<tbCategoriaPorHabilidad> tbCategoriaPorHabilidad { get; set; } = new List<tbCategoriaPorHabilidad>();

    public virtual ICollection<tbHabilidadPorFactura> tbHabilidadPorFactura { get; set; } = new List<tbHabilidadPorFactura>();

    public virtual tbTransaccion tran { get; set; }

    public virtual tbUsuarios user { get; set; }
}