// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbHorario
{
    public Guid hor_Id { get; set; }

    public int hor_DiaNumero { get; set; }

    public Guid user_Id { get; set; }

    public TimeOnly hor_HoraInicio { get; set; }

    public TimeOnly hor_HoraFin { get; set; }

    public virtual tbUsuarios user { get; set; }
}