// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbIdioma
{
    public Guid idio_Id { get; set; }

    public string idio_Descripcion { get; set; }

    public virtual ICollection<tbIdiomaItem> tbIdiomaItem { get; set; } = new List<tbIdiomaItem>();
}