// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbInfoUnicaUsuario
{
    public Guid usInf_Id { get; set; }

    public bool usInf_IgualSubInfo { get; set; }

    public string usInf_Nombre { get; set; }

    public string usInf_RutaLogo { get; set; }

    public string usInf_RutaPaginaWed { get; set; }

    public bool usInf_Verificado { get; set; }

    public Guid tipUs_Id { get; set; }

    public virtual ICollection<tbUsuarios> tbUsuarios { get; set; } = new List<tbUsuarios>();

    public virtual tbTipoUsuario tipUs { get; set; }
}