// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbNecesitan
{
    public Guid necs_Id { get; set; }

    public string necs_Nombre { get; set; }

    public string necs_Descripcion { get; set; }

    public Guid user_Id { get; set; }

    public Guid tran_Id { get; set; }

    public virtual ICollection<tbCategoriaPorNecesidad> tbCategoriaPorNecesidad { get; set; } = new List<tbCategoriaPorNecesidad>();

    public virtual tbTransaccion tran { get; set; }

    public virtual tbUsuarios user { get; set; }
}