// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbNivelEducativo
{
    public Guid nivEd_Id { get; set; }

    public string nivEd_Descripcion { get; set; }

    public virtual ICollection<tbTitulo> tbTitulo { get; set; } = new List<tbTitulo>();
}