// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbOrigen
{
    public Guid origen_Id { get; set; }

    public string origen_Descripcion { get; set; }

    public Guid tran_Id { get; set; }

    public Guid prod_Id { get; set; }

    public virtual tbProducto prod { get; set; }

    public virtual tbTransaccion tran { get; set; }

    public virtual ICollection<tbUsuarios> user { get; set; } = new List<tbUsuarios>();
}