// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbOtrosConocimientos
{
    public Guid otrCo_Id { get; set; }

    public string otrCo_Descripcion { get; set; }

    public Guid vac_Id { get; set; }

    public virtual tbVacante vac { get; set; }
}