// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbPedidoDetalle
{
    public Guid pedDet_Id { get; set; }

    public Guid ped_Id { get; set; }

    public string pedDet_Codigo { get; set; }

    public int pedDet_Cantidad { get; set; }

    public string pedDet_Descripcion { get; set; }

    public decimal pedDet_PrecioUnitario { get; set; }

    public decimal pedDet_Descuento { get; set; }

    public decimal pedDet_Impuesto { get; set; }

    public decimal pedDet_PorcentajeImpuestos { get; set; }

    public decimal pedDet_TotalPagar { get; set; }

    public Guid tipCatg_Id { get; set; }

    public virtual tbPedido ped { get; set; }

    public virtual tbProductoPorPedido tbProductoPorPedido { get; set; }

    public virtual tbServicioPorPedido tbServicioPorPedido { get; set; }

    public virtual tbTipoCatalogo tipCatg { get; set; }
}