// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbPedido
{
    public Guid ped_Id { get; set; }

    public string ped_NombreCliente { get; set; }

    public DateTime ped_FechaCreacio { get; set; }

    public DateTime ped_Fecha { get; set; }

    public decimal ped_SubTotal { get; set; }

    public decimal ped_Descuento { get; set; }

    public decimal ped_Impuesto { get; set; }

    public decimal ped_PorcentajeImpuestos { get; set; }

    public decimal ped_TotalPagar { get; set; }

    public string ped_RTN { get; set; }

    public Guid user_Id { get; set; }

    public Guid tran_Id { get; set; }

    public Guid? user_IdCliente { get; set; }

    public virtual ICollection<tbPedidoDetalle> tbPedidoDetalle { get; set; } = new List<tbPedidoDetalle>();

    public virtual tbTransaccion tran { get; set; }

    public virtual tbUsuarios user { get; set; }

    public virtual tbUsuarios user_IdClienteNavigation { get; set; }
}