// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbPrecioProducto
{
    public Guid prodPrec_Id { get; set; }

    public Guid prod_Id { get; set; }

    public decimal prodPrec_Precio { get; set; }

    public int prodPrec_CantidadInicio { get; set; }

    public int? prodPrec_CantidadFin { get; set; }

    public DateTime? prodPrec_FechaInicioDescuento { get; set; }

    public DateTime? prodPrec_FechaFinDescuento { get; set; }

    public decimal? prodPrec_Descuento { get; set; }

    public virtual tbProducto prod { get; set; }
}