// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbProducto
{
    public Guid prod_Id { get; set; }

    public string prod_Nombre { get; set; }

    public string prod_Descripcion { get; set; }

    public Guid user_Id { get; set; }

    public int prod_Codigo { get; set; }

    public int prod_Unidades { get; set; }

    public Guid tran_Id { get; set; }

    public bool prod_ActoParaMenores { get; set; }

    public DateOnly prod_FechaCreacion { get; set; }

    public DateOnly? prod_FechaVencimiento { get; set; }

    public virtual ICollection<tbCategoriaPorProducto> tbCategoriaPorProducto { get; set; } = new List<tbCategoriaPorProducto>();

    public virtual ICollection<tbOrigen> tbOrigen { get; set; } = new List<tbOrigen>();

    public virtual ICollection<tbPrecioProducto> tbPrecioProducto { get; set; } = new List<tbPrecioProducto>();

    public virtual ICollection<tbProductoPorFactura> tbProductoPorFactura { get; set; } = new List<tbProductoPorFactura>();

    public virtual ICollection<tbProductoPorPedido> tbProductoPorPedido { get; set; } = new List<tbProductoPorPedido>();

    public virtual tbTransaccion tran { get; set; }

    public virtual tbUsuarios user { get; set; }

    public virtual ICollection<tbDesperdicio> desp { get; set; } = new List<tbDesperdicio>();
}