// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbProductoPorFactura
{
    public Guid facDet_Id { get; set; }

    public Guid prod_Id { get; set; }

    public virtual tbFacturaDetalle facDet { get; set; }

    public virtual tbProducto prod { get; set; }
}