// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbProceso
{
    public Guid proc_Id { get; set; }

    public string proc_Descripcion { get; set; }

    public virtual ICollection<tbTituloProc> tbTituloProc { get; set; } = new List<tbTituloProc>();
}