// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbPuesto
{
    public Guid puest_Id { get; set; }

    public string puest_Descripcion { get; set; }

    public Guid ariaP_Id { get; set; }

    public virtual tbAriaPuesto ariaP { get; set; }

    public virtual ICollection<tbVacante> tbVacante { get; set; } = new List<tbVacante>();
}