// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbReaccion
{
    public Guid reac_Id { get; set; }

    public Guid tipReac_Id { get; set; }

    public Guid tran_Id { get; set; }

    public Guid user_Id { get; set; }

    public virtual tbTipoReaccion tipReac { get; set; }

    public virtual tbTransaccion tran { get; set; }

    public virtual tbUsuarios user { get; set; }
}