// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbRolesClaims
{
    public Guid rolClai_Id { get; set; }

    public Guid rol_Id { get; set; }

    public string rolClai_Tipo { get; set; }

    public string rolClai_Value { get; set; }

    public virtual tbRoles rol { get; set; }
}