// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbRoles
{
    public Guid rol_Id { get; set; }

    public string rol_Nombre { get; set; }

    public string rol_NombreNormalizado { get; set; }

    public virtual ICollection<tbRolesClaims> tbRolesClaims { get; set; } = new List<tbRolesClaims>();

    public virtual ICollection<tbUsuarios> user { get; set; } = new List<tbUsuarios>();
}