// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbServicioPorPedido
{
    public Guid pedDet_Id { get; set; }

    public Guid serv_Id { get; set; }

    public virtual tbPedidoDetalle pedDet { get; set; }

    public virtual tbServicio serv { get; set; }
}