// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbServicio
{
    public Guid serv_Id { get; set; }

    public string serv_Nombre { get; set; }

    public string serv_Descripcion { get; set; }

    public Guid user_Id { get; set; }

    public int serv_Codigo { get; set; }

    public Guid tran_Id { get; set; }

    public DateOnly serv_FechaCreacion { get; set; }

    public virtual ICollection<tbCategoriaPorServicio> tbCategoriaPorServicio { get; set; } = new List<tbCategoriaPorServicio>();

    public virtual ICollection<tbServicioPorFactura> tbServicioPorFactura { get; set; } = new List<tbServicioPorFactura>();

    public virtual ICollection<tbServicioPorPedido> tbServicioPorPedido { get; set; } = new List<tbServicioPorPedido>();

    public virtual tbTransaccion tran { get; set; }

    public virtual tbUsuarios user { get; set; }

    public virtual ICollection<tbDesperdicio> desp { get; set; } = new List<tbDesperdicio>();
}