// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbServicioPorFactura
{
    public Guid facDet_Id { get; set; }

    public Guid serv_Id { get; set; }

    public virtual tbFacturaDetalle facDet { get; set; }

    public virtual tbServicio serv { get; set; }
}