// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbSubCategoria
{
    public Guid subCat_Id { get; set; }

    public Guid catg_Id { get; set; }

    public string catg_Nombre { get; set; }

    public virtual tbCategoria catg { get; set; }

    public virtual ICollection<tbCategoriaPorAlquilar> tbCategoriaPorAlquilar { get; set; } = new List<tbCategoriaPorAlquilar>();

    public virtual ICollection<tbCategoriaPorHabilidad> tbCategoriaPorHabilidad { get; set; } = new List<tbCategoriaPorHabilidad>();

    public virtual ICollection<tbCategoriaPorNecesidad> tbCategoriaPorNecesidad { get; set; } = new List<tbCategoriaPorNecesidad>();

    public virtual ICollection<tbCategoriaPorProducto> tbCategoriaPorProducto { get; set; } = new List<tbCategoriaPorProducto>();

    public virtual ICollection<tbCategoriaPorServicio> tbCategoriaPorServicio { get; set; } = new List<tbCategoriaPorServicio>();

    public virtual ICollection<tbCategoriaPorVenta> tbCategoriaPorVenta { get; set; } = new List<tbCategoriaPorVenta>();
}