// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbSubdivicionLugar
{
    public Guid subLug_Id { get; set; }

    public string subLug_Nombre { get; set; }

    public Guid catSub_Id { get; set; }

    public Guid lug_Id { get; set; }

    public virtual tbCategoriaSubdivicion catSub { get; set; }

    public virtual tbLugar lug { get; set; }

    public virtual ICollection<tbUbicacion> tbUbicacion { get; set; } = new List<tbUbicacion>();
}