// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbTipoTelefono
{
    public Guid tipTel_Id { get; set; }

    public string tipTel_Descripcion { get; set; }

    public virtual ICollection<tbUsuarioTelefono> tbUsuarioTelefono { get; set; } = new List<tbUsuarioTelefono>();
}