// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbTituloProc
{
    public Guid tiProc_Id { get; set; }

    public Guid titu_Id { get; set; }

    public Guid proc_Id { get; set; }

    public virtual tbProceso proc { get; set; }

    public virtual tbTitulo titu { get; set; }
}