// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbTipoToken
{
    public Guid tipToke_Id { get; set; }

    public string tipToke_Descripcion { get; set; }

    public virtual ICollection<tbUsuariosTokens> tbUsuariosTokens { get; set; } = new List<tbUsuariosTokens>();
}