// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbTipoTransaccion
{
    public Guid tipTran_Id { get; set; }

    public string tipTran_Nombre { get; set; }

    public virtual ICollection<tbTransaccion> tbTransaccion { get; set; } = new List<tbTransaccion>();
}