// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbTipoPago
{
    public Guid tipPag_Id { get; set; }

    public string tipPag_Descripcion { get; set; }

    public virtual ICollection<tbFactura> tbFactura { get; set; } = new List<tbFactura>();
}