// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbTipoReaccion
{
    public Guid tipReac_Id { get; set; }

    public Guid catReac_Id { get; set; }

    public string tipReac_Descripcion { get; set; }

    public virtual tbCategoriaReaccion catReac { get; set; }

    public virtual ICollection<tbReaccion> tbReaccion { get; set; } = new List<tbReaccion>();
}