// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbTiempo
{
    public Guid tiemp_Id { get; set; }

    public string tiemp_Descripcion { get; set; }

    public virtual ICollection<tbAlquilerServicios> tbAlquilerServicios { get; set; } = new List<tbAlquilerServicios>();
}