// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbTitulo
{
    public Guid titu_Id { get; set; }

    public string titu_Descripcion { get; set; }

    public Guid? ariaP_Id { get; set; }

    public Guid nivEd_Id { get; set; }

    public virtual tbAriaPuesto ariaP { get; set; }

    public virtual tbNivelEducativo nivEd { get; set; }

    public virtual ICollection<tbEducacion> tbEducacion { get; set; } = new List<tbEducacion>();

    public virtual ICollection<tbTituloProc> tbTituloProc { get; set; } = new List<tbTituloProc>();
}