// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbTransaccion
{
    public Guid tran_Id { get; set; }

    public Guid tipTran_Id { get; set; }

    public virtual ICollection<tbAlquilerServicios> tbAlquilerServicios { get; set; } = new List<tbAlquilerServicios>();

    public virtual ICollection<tbCatalogoImagen> tbCatalogoImagen { get; set; } = new List<tbCatalogoImagen>();

    public virtual ICollection<tbDesperdicio> tbDesperdicio { get; set; } = new List<tbDesperdicio>();

    public virtual ICollection<tbEvento> tbEvento { get; set; } = new List<tbEvento>();

    public virtual ICollection<tbFactura> tbFactura { get; set; } = new List<tbFactura>();

    public virtual ICollection<tbHabilidad> tbHabilidad { get; set; } = new List<tbHabilidad>();

    public virtual ICollection<tbNecesitan> tbNecesitan { get; set; } = new List<tbNecesitan>();

    public virtual ICollection<tbOrigen> tbOrigen { get; set; } = new List<tbOrigen>();

    public virtual ICollection<tbPedido> tbPedido { get; set; } = new List<tbPedido>();

    public virtual ICollection<tbProducto> tbProducto { get; set; } = new List<tbProducto>();

    public virtual ICollection<tbReaccion> tbReaccion { get; set; } = new List<tbReaccion>();

    public virtual ICollection<tbServicio> tbServicio { get; set; } = new List<tbServicio>();

    public virtual ICollection<tbVentaRelampago> tbVentaRelampago { get; set; } = new List<tbVentaRelampago>();

    public virtual tbTipoTransaccion tipTran { get; set; }
}