// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbUbicacion
{
    public Guid ubc_Id { get; set; }

    public string ubc_Latitud { get; set; }

    public string ubc_Longitub { get; set; }

    public Guid subLug_Id { get; set; }

    public virtual tbSubdivicionLugar subLug { get; set; }

    public virtual ICollection<tbEvento> tbEvento { get; set; } = new List<tbEvento>();

    public virtual ICollection<tbUsuarios> tbUsuarios { get; set; } = new List<tbUsuarios>();

    public virtual ICollection<tbVentaRelampago> tbVentaRelampago { get; set; } = new List<tbVentaRelampago>();
}