// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbUsuarios
{
    public Guid user_Id { get; set; }

    public Guid usInf_Id { get; set; }

    public string user_Descripcion { get; set; }

    public Guid ubc_Id { get; set; }

    public string user_Identificacion { get; set; }

    public Guid tipIde_Id { get; set; }

    public string user_NombreUsuario { get; set; }

    public string user_Password { get; set; }

    public string user_PasswordSal { get; set; }

    public DateTime? user_FechaCreacion { get; set; }

    public string user_Correo { get; set; }

    public string user_Facebook { get; set; }

    public string user_Intagram { get; set; }

    public bool user_WhatsApp { get; set; }

    public bool user_Envio { get; set; }

    public bool user_UsuarioPrincipal { get; set; }

    public bool user_Verificado { get; set; }

    public virtual ICollection<tbAlquilerServicios> tbAlquilerServicios { get; set; } = new List<tbAlquilerServicios>();

    public virtual ICollection<tbCategoriaItem> tbCategoriaItem { get; set; } = new List<tbCategoriaItem>();

    public virtual ICollection<tbDesperdicio> tbDesperdicio { get; set; } = new List<tbDesperdicio>();

    public virtual ICollection<tbEvento> tbEvento { get; set; } = new List<tbEvento>();

    public virtual ICollection<tbFactura> tbFacturauser { get; set; } = new List<tbFactura>();

    public virtual ICollection<tbFactura> tbFacturauser_IdClienteNavigation { get; set; } = new List<tbFactura>();

    public virtual ICollection<tbHabilidad> tbHabilidad { get; set; } = new List<tbHabilidad>();

    public virtual ICollection<tbHorario> tbHorario { get; set; } = new List<tbHorario>();

    public virtual ICollection<tbNecesitan> tbNecesitan { get; set; } = new List<tbNecesitan>();

    public virtual ICollection<tbPedido> tbPedidouser { get; set; } = new List<tbPedido>();

    public virtual ICollection<tbPedido> tbPedidouser_IdClienteNavigation { get; set; } = new List<tbPedido>();

    public virtual ICollection<tbProducto> tbProducto { get; set; } = new List<tbProducto>();

    public virtual ICollection<tbReaccion> tbReaccion { get; set; } = new List<tbReaccion>();

    public virtual ICollection<tbServicio> tbServicio { get; set; } = new List<tbServicio>();

    public virtual ICollection<tbUsuarioTelefono> tbUsuarioTelefono { get; set; } = new List<tbUsuarioTelefono>();

    public virtual ICollection<tbVacante> tbVacante { get; set; } = new List<tbVacante>();

    public virtual ICollection<tbVentaRelampago> tbVentaRelampago { get; set; } = new List<tbVentaRelampago>();

    public virtual tbTipoIdentificacion tipIde { get; set; }

    public virtual tbUbicacion ubc { get; set; }

    public virtual tbInfoUnicaUsuario usInf { get; set; }

    public virtual ICollection<tbEvento> even { get; set; } = new List<tbEvento>();

    public virtual ICollection<tbOrigen> origen { get; set; } = new List<tbOrigen>();
}