// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbUsuariosClaims
{
    public Guid userClai_Id { get; set; }

    public Guid user_Id { get; set; }

    public string userClai_Tipo { get; set; }

    public string userClai_Value { get; set; }

    public virtual tbUsuarios user { get; set; }
}