// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbUsuariosTokens
{
    public Guid user_Id { get; set; }

    public Guid tipToke_Id { get; set; }

    public string userToke_Token { get; set; }

    public virtual tbTipoToken tipToke { get; set; }

    public virtual tbUsuarios user { get; set; }
}