// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiCircularGraphQL.Domain.Entities;

public partial class tbVentaRelampago
{
    public Guid ventR_Id { get; set; }

    public string ventR_Titulo { get; set; }

    public string ventR_Descripcion { get; set; }

    public DateTime ventR_Fecha { get; set; }

    public decimal ventR_Precio { get; set; }

    public bool ventR_Agotado { get; set; }

    public Guid user_Id { get; set; }

    public Guid tran_Id { get; set; }

    public Guid ubc_Id { get; set; }

    public virtual ICollection<tbCategoriaPorVenta> tbCategoriaPorVenta { get; set; } = new List<tbCategoriaPorVenta>();

    public virtual tbTransaccion tran { get; set; }

    public virtual tbUbicacion ubc { get; set; }

    public virtual tbUsuarios user { get; set; }
}