// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbAriaPuesto
    {
        public tbAriaPuesto()
        {
            tbExperiencia = new HashSet<tbExperiencia>();
            tbPuesto = new HashSet<tbPuesto>();
            tbTitulo = new HashSet<tbTitulo>();
            tbVacante = new HashSet<tbVacante>();
        }

        public Guid ariaP_Id { get; set; }
        public string ariaP_Descripcion { get; set; }

        public virtual ICollection<tbExperiencia> tbExperiencia { get; set; }
        public virtual ICollection<tbPuesto> tbPuesto { get; set; }
        public virtual ICollection<tbTitulo> tbTitulo { get; set; }
        public virtual ICollection<tbVacante> tbVacante { get; set; }
    }
}