// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbArrendamientoPor
{
    public int arr_Id { get; set; }

    public string arr_Descripcion { get; set; }

    public virtual ICollection<tbPrecio> tbPrecio { get; set; } = new List<tbPrecio>();
}