// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbAria
    {
        public tbAria()
        {
            tbRugro = new HashSet<tbRugro>();
        }

        public int aria_Id { get; set; }
        public string aria_Nombre { get; set; }

        public virtual ICollection<tbRugro> tbRugro { get; set; }
    }
}