// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbAriaPuesto
{
    public int ariaP_Id { get; set; }

    public string ariaP_Descripcion { get; set; }

    public virtual ICollection<tbExperiencia> tbExperiencia { get; set; } = new List<tbExperiencia>();

    public virtual ICollection<tbPuesto> tbPuesto { get; set; } = new List<tbPuesto>();

    public virtual ICollection<tbTitulo> tbTitulo { get; set; } = new List<tbTitulo>();

    public virtual ICollection<tbVacante> tbVacante { get; set; } = new List<tbVacante>();
}