// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbCategoriaLugar
    {
        public tbCategoriaLugar()
        {
            tbLugar = new HashSet<tbLugar>();
        }

        public int catLug_Id { get; set; }
        public string catLug_Nombre { get; set; }

        public virtual ICollection<tbLugar> tbLugar { get; set; }
    }
}