// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbCargo
    {
        public Guid carg_Id { get; set; }
        public string carg_Descripcion { get; set; }
        public Guid vac_Id { get; set; }

        public virtual tbVacante vac { get; set; }
    }
}