// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbCatalogoPorUsuario
{
    public int catUsua_Id { get; set; }

    public int tipCatg_Id { get; set; }

    public int tipUs_Id { get; set; }

    public virtual tbTipoCatalogo tipCatg { get; set; }

    public virtual tbTipoUsuario tipUs { get; set; }
}