// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbCatalogo
    {
        public tbCatalogo()
        {
            Inversecatg_IdDesperdicioNavigation = new HashSet<tbCatalogo>();
            tbCatalogoImagen = new HashSet<tbCatalogoImagen>();
            tbCatalogoOng = new HashSet<tbCatalogoOng>();
            tbCatalogoReaccion = new HashSet<tbCatalogoReaccion>();
            tbContribuyente = new HashSet<tbContribuyente>();
            tbGuardar = new HashSet<tbGuardar>();
            tbPrecio = new HashSet<tbPrecio>();
        }

        public Guid catg_Id { get; set; }
        public string catg_Nombre { get; set; }
        public string catg_Descripcion { get; set; }
        public string catg_JsonReaccion { get; set; }
        public Guid? catg_IdDesperdicio { get; set; }
        public Guid categ_Id { get; set; }
        public Guid user_Id { get; set; }
        public byte catg_EdadActaParaVer { get; set; }
        public DateTime catg_FechaCreacion { get; set; }
        public bool catag_EsGratis { get; set; }

        public virtual tbCategoria categ { get; set; }
        public virtual tbCatalogo catg_IdDesperdicioNavigation { get; set; }
        public virtual tbUsuarios user { get; set; }
        public virtual ICollection<tbCatalogo> Inversecatg_IdDesperdicioNavigation { get; set; }
        public virtual ICollection<tbCatalogoImagen> tbCatalogoImagen { get; set; }
        public virtual ICollection<tbCatalogoOng> tbCatalogoOng { get; set; }
        public virtual ICollection<tbCatalogoReaccion> tbCatalogoReaccion { get; set; }
        public virtual ICollection<tbContribuyente> tbContribuyente { get; set; }
        public virtual ICollection<tbGuardar> tbGuardar { get; set; }
        public virtual ICollection<tbPrecio> tbPrecio { get; set; }
    }
}