// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbCatalogo
{
    public int catg_Id { get; set; }

    public string catg_Nombre { get; set; }

    public string catg_Descripcion { get; set; }

    public string catg_JsonReaccion { get; set; }

    public int? catg_IdDesperdicio { get; set; }

    public int categ_Id { get; set; }

    public int user_Id { get; set; }

    public byte catg_EdadActaParaVer { get; set; }

    public DateTime catg_FechaCreacion { get; set; }

    public virtual ICollection<tbCatalogo> Inversecatg_IdDesperdicioNavigation { get; set; } = new List<tbCatalogo>();

    public virtual tbCategoria categ { get; set; }

    public virtual tbCatalogo catg_IdDesperdicioNavigation { get; set; }

    public virtual ICollection<tbCatalogoOng> tbCatalogoOng { get; set; } = new List<tbCatalogoOng>();

    public virtual ICollection<tbCatalogoReaccion> tbCatalogoReaccion { get; set; } = new List<tbCatalogoReaccion>();

    public virtual ICollection<tbContribuyente> tbContribuyente { get; set; } = new List<tbContribuyente>();

    public virtual ICollection<tbGuardar> tbGuardar { get; set; } = new List<tbGuardar>();

    public virtual ICollection<tbOrigenImagen> tbOrigenImagen { get; set; } = new List<tbOrigenImagen>();

    public virtual ICollection<tbPrecio> tbPrecio { get; set; } = new List<tbPrecio>();

    public virtual tbUsuarios user { get; set; }
}