// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbCategoriaItem
    {
        public int catgItem_Id { get; set; }
        public int catg_Id { get; set; }
        public int user_Id { get; set; }

        public virtual tbCategoria catg { get; set; }
        public virtual tbUsuarios user { get; set; }
    }
}