// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbContribuyente
{
    public int contr_Id { get; set; }

    public string contr_Descripcion { get; set; }

    public int prod_Id { get; set; }

    public int user_Id { get; set; }

    public virtual tbProducto prod { get; set; }

    public virtual tbUsuarios user { get; set; }
}