// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbConfiguracion
    {
        public int conf_Id { get; set; }
        public string conf_Nombre { get; set; }
        public string conf_Valor { get; set; }
        public string conf_Descripcion { get; set; }
    }
}