// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbDesperdicioImagen
    {
        public int despIm_Id { get; set; }
        public string despIm_Ruta { get; set; }
        public int desp_Id { get; set; }

        public virtual tbDesperdicio desp { get; set; }
    }
}