// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbDesperdicioCatedoria
    {
        public tbDesperdicioCatedoria()
        {
            tbDesperdicio = new HashSet<tbDesperdicio>();
        }

        public int desCa_Id { get; set; }
        public string desCa_Descripcion { get; set; }

        public virtual ICollection<tbDesperdicio> tbDesperdicio { get; set; }
    }
}