// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbEducacion
    {
        public Guid ed_Id { get; set; }
        public bool ed_Requerido { get; set; }
        public Guid titu_Id { get; set; }
        public Guid vac_Id { get; set; }

        public virtual tbTitulo titu { get; set; }
        public virtual tbVacante vac { get; set; }
    }
}