// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbGenero
    {
        public tbGenero()
        {
            tbVacante = new HashSet<tbVacante>();
        }

        public int gene_Id { get; set; }
        public string gene_Descripcion { get; set; }

        public virtual ICollection<tbVacante> tbVacante { get; set; }
    }
}