// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbIdioma
    {
        public int idio_Id { get; set; }
        public string idio_Descripcion { get; set; }
    }
}