// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbIdiomaItem
    {
        public Guid idItm_Id { get; set; }
        public Guid idio_Id { get; set; }
        public Guid vac_Id { get; set; }

        public virtual tbIdioma idio { get; set; }
        public virtual tbVacante vac { get; set; }
    }
}