// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbLogroEventoCategoria
    {
        public tbLogroEventoCategoria()
        {
            tbOngEvento = new HashSet<tbOngEvento>();
        }

        public int logCa_Id { get; set; }
        public string logCa_Descripcion { get; set; }

        public virtual ICollection<tbOngEvento> tbOngEvento { get; set; }
    }
}