// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbLugar
{
    public int lug_Id { get; set; }

    public string lug_Nombre { get; set; }

    public int catLug_Id { get; set; }

    public int muni_Id { get; set; }

    public virtual tbCategoriaLugar catLug { get; set; }

    public virtual tbMunicipio muni { get; set; }

    public virtual ICollection<tbSubdivicionLugar> tbSubdivicionLugar { get; set; } = new List<tbSubdivicionLugar>();
}