// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbNeceitaCatedoria
{
    public int nesCa_Id { get; set; }

    public string nesCa_Descripcion { get; set; }

    public virtual ICollection<tbNecesita> tbNecesita { get; set; } = new List<tbNecesita>();
}