// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbNivelEducativo
    {
        public tbNivelEducativo()
        {
            tbTitulo = new HashSet<tbTitulo>();
        }

        public int nivEd_Id { get; set; }
        public string nivEd_Descripcion { get; set; }

        public virtual ICollection<tbTitulo> tbTitulo { get; set; }
    }
}