// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbOngEventoImagen
    {
        public int ongIm_Id { get; set; }
        public string ongIm_Ruta { get; set; }
        public int ongEv_Id { get; set; }

        public virtual tbOngEvento ongEv { get; set; }
    }
}