// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbOrigen
{
    public int orig_Id { get; set; }

    public string orig_Descripcion { get; set; }

    public string orig_Imagen { get; set; }

    public int prod_Id { get; set; }

    public virtual tbProducto prod { get; set; }
}