// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbOrigeDesperdicio
    {
        public tbOrigeDesperdicio()
        {
            tbDesperdicio = new HashSet<tbDesperdicio>();
        }

        public int oriDe_Id { get; set; }
        public string oriDe_Descripcion { get; set; }

        public virtual ICollection<tbDesperdicio> tbDesperdicio { get; set; }
    }
}