// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbOrigenImagen
{
    public int catImg_Id { get; set; }

    public int catg_Id { get; set; }

    public string catImg_RutaImagen { get; set; }

    public virtual tbCatalogo catg { get; set; }
}