// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbOrigenServicio
{
    public int oriS_Id { get; set; }

    public string oriS_Descripcion { get; set; }

    public virtual ICollection<tbServicio> tbServicio { get; set; } = new List<tbServicio>();
}