// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbOtrosConocimientos
{
    public int otrCo_Id { get; set; }

    public string otrCo_Descripcion { get; set; }

    public int vac_Id { get; set; }

    public virtual tbVacante vac { get; set; }
}