// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbPais
    {
        public tbPais()
        {
            tbDepartamento = new HashSet<tbDepartamento>();
        }

        public int pais_Id { get; set; }
        public string pais_Nombre { get; set; }
        public string pais_Abrebiatura { get; set; }

        public virtual ICollection<tbDepartamento> tbDepartamento { get; set; }
    }
}