// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbPrecio
{
    public int prec_Id { get; set; }

    public decimal prec_Inicial { get; set; }

    public decimal prec_Final { get; set; }

    public int prec_Cantidad { get; set; }

    public int tipPag_Id { get; set; }

    public int? arr_Id { get; set; }

    public int catg_Id { get; set; }

    public virtual tbArrendamientoPor arr { get; set; }

    public virtual tbCatalogo catg { get; set; }

    public virtual tbTipoPago tipPag { get; set; }
}