// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbProdCategoria
{
    public int proCa_Id { get; set; }

    public string proCa_Descripcion { get; set; }

    public virtual ICollection<tbProducto> tbProducto { get; set; } = new List<tbProducto>();
}