// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbPrecio
    {
        public Guid prec_Id { get; set; }
        public decimal prec_Inicial { get; set; }
        public decimal prec_Final { get; set; }
        public int prec_Cantidad { get; set; }
        public Guid tipPag_Id { get; set; }
        public Guid catg_Id { get; set; }

        public virtual tbCatalogo catg { get; set; }
        public virtual tbTipoPago tipPag { get; set; }
    }
}