// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbProceso
    {
        public tbProceso()
        {
            tbTituloProc = new HashSet<tbTituloProc>();
        }

        public int proc_Id { get; set; }
        public string proc_Descripcion { get; set; }

        public virtual ICollection<tbTituloProc> tbTituloProc { get; set; }
    }
}