// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbProducto
    {
        public tbProducto()
        {
            tbContribuyente = new HashSet<tbContribuyente>();
            tbDesperdicio = new HashSet<tbDesperdicio>();
            tbOrigen = new HashSet<tbOrigen>();
            tbProductoImagen = new HashSet<tbProductoImagen>();
        }

        public int prod_Id { get; set; }
        public string prod_Nombre { get; set; }
        public string prod_Descripcion { get; set; }
        public decimal prod_Precio { get; set; }
        public bool prod_Reporte { get; set; }
        public string prod_JsonReaccion { get; set; }
        public string prod_JsonReporte { get; set; }
        public string prod_Imagen { get; set; }
        public bool prod_Existencia { get; set; }
        public bool prod_Negociado { get; set; }
        public int proCa_Id { get; set; }
        public int user_Id { get; set; }

        public virtual tbProdCategoria proCa { get; set; }
        public virtual tbUsuarios user { get; set; }
        public virtual ICollection<tbContribuyente> tbContribuyente { get; set; }
        public virtual ICollection<tbDesperdicio> tbDesperdicio { get; set; }
        public virtual ICollection<tbOrigen> tbOrigen { get; set; }
        public virtual ICollection<tbProductoImagen> tbProductoImagen { get; set; }
    }
}