// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbProductoImagen
{
    public int proIm_Id { get; set; }

    public string proIm_Ruta { get; set; }

    public int prod_Id { get; set; }

    public virtual tbProducto prod { get; set; }
}