// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbPuesto
    {
        public tbPuesto()
        {
            tbVacante = new HashSet<tbVacante>();
        }

        public int puest_Id { get; set; }
        public string puest_Descripcion { get; set; }
        public int ariaP_Id { get; set; }

        public virtual tbAriaPuesto ariaP { get; set; }
        public virtual ICollection<tbVacante> tbVacante { get; set; }
    }
}