// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbRugro
    {
        public tbRugro()
        {
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int rug_Id { get; set; }
        public string rug_Nombre { get; set; }
        public int aria_Id { get; set; }

        public virtual tbAria aria { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}