// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbServicio
{
    public int serv_Id { get; set; }

    public string serv_Nombre { get; set; }

    public string serv_Descripcion { get; set; }

    public decimal serv_Precio { get; set; }

    public bool serv_Negociado { get; set; }

    public string serv_JsonReaccion { get; set; }

    public bool serv_Reporte { get; set; }

    public string serv_JsonReporte { get; set; }

    public string serv_Imagen { get; set; }

    public int oriS_Id { get; set; }

    public int serCa_Id { get; set; }

    public int tipSe_Id { get; set; }

    public int user_Id { get; set; }

    public virtual tbOrigenServicio oriS { get; set; }

    public virtual tbServicioCategoria serCa { get; set; }

    public virtual ICollection<tbDesperdicio> tbDesperdicio { get; set; } = new List<tbDesperdicio>();

    public virtual ICollection<tbServicioImagen> tbServicioImagen { get; set; } = new List<tbServicioImagen>();

    public virtual tbTipoServicio tipSe { get; set; }

    public virtual tbUsuarios user { get; set; }
}