// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbServicioImagen
{
    public int serIm_Id { get; set; }

    public string serIm_Ruta { get; set; }

    public int serv_Id { get; set; }

    public virtual tbServicio serv { get; set; }
}