// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbTituloProc
{
    public int tiProc_Id { get; set; }

    public int titu_Id { get; set; }

    public int proc_Id { get; set; }

    public virtual tbProceso proc { get; set; }

    public virtual tbTitulo titu { get; set; }
}