// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbTipoServicio
    {
        public tbTipoServicio()
        {
            tbServicio = new HashSet<tbServicio>();
        }

        public int tipSe_Id { get; set; }
        public string tipSe_Descripcion { get; set; }

        public virtual ICollection<tbServicio> tbServicio { get; set; }
    }
}