// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbTipoContrato
    {
        public tbTipoContrato()
        {
            tbVacante = new HashSet<tbVacante>();
        }

        public Guid tipC_Id { get; set; }
        public string tipC_Descripcion { get; set; }

        public virtual ICollection<tbVacante> tbVacante { get; set; }
    }
}