// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbTipoPago
{
    public int tipPag_Id { get; set; }

    public string tipPag_Descripcion { get; set; }

    public virtual ICollection<tbPrecio> tbPrecio { get; set; } = new List<tbPrecio>();
}