// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbTipoReaccion
    {
        public Guid tipRea_Id { get; set; }
        public string tipRea_Descripcion { get; set; }
    }
}