// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbTipoUsuario
    {
        public tbTipoUsuario()
        {
            tbInfoUnicaUsuario = new HashSet<tbInfoUnicaUsuario>();
        }

        public int tipUs_Id { get; set; }
        public string tipUs_Descripcion { get; set; }

        public virtual ICollection<tbInfoUnicaUsuario> tbInfoUnicaUsuario { get; set; }
    }
}