// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbTipoIdentificacion
    {
        public tbTipoIdentificacion()
        {
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public Guid tipIde_Id { get; set; }
        public string tipIde_Descripcion { get; set; }

        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}