// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbUbicacion
{
    public int ubc_Id { get; set; }

    public string ubc_Latitud { get; set; }

    public string ubc_Longitub { get; set; }

    public int subLug_Id { get; set; }

    public virtual tbSubdivicionLugar subLug { get; set; }

    public virtual ICollection<tbCatalogoOng> tbCatalogoOng { get; set; } = new List<tbCatalogoOng>();

    public virtual ICollection<tbUsuarios> tbUsuarios { get; set; } = new List<tbUsuarios>();
}