// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbUbicacion
    {
        public tbUbicacion()
        {
            tbCatalogoOng = new HashSet<tbCatalogoOng>();
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public Guid ubc_Id { get; set; }
        public string ubc_Latitud { get; set; }
        public string ubc_Longitub { get; set; }
        public Guid subLug_Id { get; set; }

        public virtual tbSubdivicionLugar subLug { get; set; }
        public virtual ICollection<tbCatalogoOng> tbCatalogoOng { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}