// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbUsuarioTelefono
    {
        public Guid usTel_Id { get; set; }
        public Guid tipTel_Id { get; set; }
        public Guid user_Id { get; set; }
        public string usTel_Numero { get; set; }

        public virtual tbTipoTelefono tipTel { get; set; }
        public virtual tbUsuarios user { get; set; }
    }
}