// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            tbCatalogo = new HashSet<tbCatalogo>();
            tbCatalogoReaccion = new HashSet<tbCatalogoReaccion>();
            tbCategoriaItem = new HashSet<tbCategoriaItem>();
            tbContribuyente = new HashSet<tbContribuyente>();
            tbGuardar = new HashSet<tbGuardar>();
            tbHorario = new HashSet<tbHorario>();
            tbUsuarioTelefono = new HashSet<tbUsuarioTelefono>();
            tbVacante = new HashSet<tbVacante>();
        }

        public Guid user_Id { get; set; }
        public Guid usInf_Id { get; set; }
        public string user_Descripcion { get; set; }
        public Guid ubc_Id { get; set; }
        public string user_Identificacion { get; set; }
        public Guid tipIde_Id { get; set; }
        public string user_NombreUsuario { get; set; }
        public string user_Password { get; set; }
        public string user_PasswordSal { get; set; }
        public DateTime? user_FechaCreacion { get; set; }
        public string user_Correo { get; set; }
        public string user_Facebook { get; set; }
        public string user_Intagram { get; set; }
        public bool user_WhatsApp { get; set; }
        public bool user_Envio { get; set; }
        public bool user_UsuarioPrincipal { get; set; }
        public bool user_Verificado { get; set; }

        public virtual tbTipoIdentificacion tipIde { get; set; }
        public virtual tbUbicacion ubc { get; set; }
        public virtual tbInfoUnicaUsuario usInf { get; set; }
        public virtual ICollection<tbCatalogo> tbCatalogo { get; set; }
        public virtual ICollection<tbCatalogoReaccion> tbCatalogoReaccion { get; set; }
        public virtual ICollection<tbCategoriaItem> tbCategoriaItem { get; set; }
        public virtual ICollection<tbContribuyente> tbContribuyente { get; set; }
        public virtual ICollection<tbGuardar> tbGuardar { get; set; }
        public virtual ICollection<tbHorario> tbHorario { get; set; }
        public virtual ICollection<tbUsuarioTelefono> tbUsuarioTelefono { get; set; }
        public virtual ICollection<tbVacante> tbVacante { get; set; }
    }
}