// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCircular.Entities.Entities;

public partial class tbUsuarios
{
    public int user_Id { get; set; }

    public int usInf_Id { get; set; }

    public string user_Descripcion { get; set; }

    public int ubc_Id { get; set; }

    public string user_Identificacion { get; set; }

    public int tipIde_Id { get; set; }

    public string user_NombreUsuario { get; set; }

    public string user_Password { get; set; }

    public string user_PasswordSal { get; set; }

    public DateTime? user_FechaCreacion { get; set; }

    public string user_Correo { get; set; }

    public string user_Facebook { get; set; }

    public string user_Intagram { get; set; }

    public bool user_WhatsApp { get; set; }

    public bool user_Envio { get; set; }

    public bool user_UsuarioPrincipal { get; set; }

    public bool user_Verificado { get; set; }

    public virtual ICollection<tbCatalogo> tbCatalogo { get; set; } = new List<tbCatalogo>();

    public virtual ICollection<tbCatalogoReaccion> tbCatalogoReaccion { get; set; } = new List<tbCatalogoReaccion>();

    public virtual ICollection<tbCategoriaItem> tbCategoriaItem { get; set; } = new List<tbCategoriaItem>();

    public virtual ICollection<tbContribuyente> tbContribuyente { get; set; } = new List<tbContribuyente>();

    public virtual ICollection<tbGuardar> tbGuardar { get; set; } = new List<tbGuardar>();

    public virtual ICollection<tbHorario> tbHorario { get; set; } = new List<tbHorario>();

    public virtual ICollection<tbUsuarioTelefono> tbUsuarioTelefono { get; set; } = new List<tbUsuarioTelefono>();

    public virtual ICollection<tbVacante> tbVacante { get; set; } = new List<tbVacante>();

    public virtual tbUbicacion ubc { get; set; }

    public virtual tbInfoUnicaUsuario usInf { get; set; }
}